{"level":"error","message":"Migration failed: __dirname is not defined","stack":"ReferenceError: __dirname is not defined\n    at migrateDatabase (C:\\Projetos\\zeplo\\backend\\src\\database\\migrate.ts:13:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-04-28 17:40:26"}
{"code":"42703","file":"parse_target.c","length":132,"level":"error","line":"1066","message":"Database seed failed: insert into \"users\" (\"created_at\", \"email\", \"name\", \"password\", \"plan\", \"trial_end_date\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning \"id\" - column \"trial_end_date\" of relation \"users\" does not exist","name":"error","position":"73","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"users\" (\"created_at\", \"email\", \"name\", \"password\", \"plan\", \"trial_end_date\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning \"id\" - column \"trial_end_date\" of relation \"users\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 17:40:44"}
{"level":"error","message":"API request failed: GET /instance/info/test-1745876012940","timestamp":"2025-04-28 18:33:38"}
{"level":"error","message":"Status: 404","timestamp":"2025-04-28 18:33:38"}
{"error":"Not Found","level":"error","message":"Data:","response":{"message":["Cannot GET /instance/info/test-1745876012940"]},"status":404,"timestamp":"2025-04-28 18:33:38"}
{"level":"error","message":"API request failed: GET /group/fetchAllGroups/test-1745876012940?getParticipants=true","timestamp":"2025-04-28 18:33:58"}
{"level":"error","message":"Error:","timestamp":"2025-04-28 18:33:58"}
{"level":"error","message":"API request failed: GET /contact/get/test-1745876012940","timestamp":"2025-04-28 18:33:58"}
{"level":"error","message":"Status: 404","timestamp":"2025-04-28 18:33:58"}
{"error":"Not Found","level":"error","message":"Data:","response":{"message":["Cannot GET /contact/get/test-1745876012940"]},"status":404,"timestamp":"2025-04-28 18:33:58"}
{"level":"error","message":"Instance test-instance not found","timestamp":"2025-04-28 18:34:01"}
{"level":"error","message":"❌ Register test failed:","timestamp":"2025-04-28 18:34:02"}
{"level":"error","message":"❌ Login test failed:","timestamp":"2025-04-28 18:34:02"}
{"code":"42703","file":"parse_target.c","length":132,"level":"error","line":"1066","message":"Registration error: insert into \"users\" (\"created_at\", \"email\", \"name\", \"password\", \"plan\", \"trial_end_date\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning \"id\" - column \"trial_end_date\" of relation \"users\" does not exist","name":"error","position":"73","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"users\" (\"created_at\", \"email\", \"name\", \"password\", \"plan\", \"trial_end_date\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning \"id\" - column \"trial_end_date\" of relation \"users\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 18:57:19"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 18:57:19"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 18:57:19"}
{"code":"42703","file":"parse_target.c","length":132,"level":"error","line":"1066","message":"Registration error: insert into \"users\" (\"created_at\", \"email\", \"name\", \"password\", \"plan\", \"trial_end_date\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning \"id\" - column \"trial_end_date\" of relation \"users\" does not exist","name":"error","position":"73","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"users\" (\"created_at\", \"email\", \"name\", \"password\", \"plan\", \"trial_end_date\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning \"id\" - column \"trial_end_date\" of relation \"users\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:03:33"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values (DEFAULT, $1, $2, $3) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:03:34"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values (DEFAULT, $1, $2, $3) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:03:34"}
{"level":"error","message":"API request failed: GET /instance/info/test-1745877887663","timestamp":"2025-04-28 19:04:53"}
{"level":"error","message":"Status: 404","timestamp":"2025-04-28 19:04:53"}
{"error":"Not Found","level":"error","message":"Data:","response":{"message":["Cannot GET /instance/info/test-1745877887663"]},"status":404,"timestamp":"2025-04-28 19:04:53"}
{"level":"error","message":"API request failed: GET /group/fetchAllGroups/test-1745877887663?getParticipants=true","timestamp":"2025-04-28 19:05:13"}
{"level":"error","message":"Error:","timestamp":"2025-04-28 19:05:13"}
{"level":"error","message":"API request failed: GET /contact/get/test-1745877887663","timestamp":"2025-04-28 19:05:13"}
{"level":"error","message":"Status: 404","timestamp":"2025-04-28 19:05:13"}
{"error":"Not Found","level":"error","message":"Data:","response":{"message":["Cannot GET /contact/get/test-1745877887663"]},"status":404,"timestamp":"2025-04-28 19:05:13"}
{"level":"error","message":"Instance test-instance not found","timestamp":"2025-04-28 19:05:16"}
{"level":"error","message":"❌ Register test failed:","timestamp":"2025-04-28 19:05:17"}
{"level":"error","message":"❌ Login test failed:","timestamp":"2025-04-28 19:05:17"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values (DEFAULT, $1, DEFAULT, $2) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:17:20"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values (DEFAULT, $1, DEFAULT, $2) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:17:20"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values (DEFAULT, $1, DEFAULT, $2) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:18:04"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values (DEFAULT, $1, DEFAULT, $2) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:18:04"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:27:08"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:27:08"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:28:18"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:28:18"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:28:47"}
{"level":"error","message":"Error creating flow: insert into \"flows\" (\"description\", \"is_draft\", \"name\", \"user_id\") values ($1, $2, $3, $4) returning * - column \"description\" of relation \"flows\" does not exist","timestamp":"2025-04-28 19:28:47"}
{"level":"error","message":"Migration failed: __dirname is not defined","stack":"ReferenceError: __dirname is not defined\n    at migrateDatabase (C:\\Projetos\\zeplo\\backend\\src\\database\\migrate.ts:13:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-04-28 19:44:56"}
{"level":"error","message":"Migration failed: __dirname is not defined","stack":"ReferenceError: __dirname is not defined\n    at migrateDatabase (C:\\Projetos\\zeplo\\backend\\src\\database\\migrate.ts:13:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-04-28 19:46:42"}
{"code":"42P07","file":"heap.c","length":99,"level":"error","line":"1149","message":"Migration failed: create table \"users\" (\"id\" serial primary key, \"name\" varchar(255) not null, \"email\" varchar(255) not null, \"password\" varchar(255) not null, \"plan\" text check (\"plan\" in ('free', 'basic', 'premium', 'business')) default 'free', \"trial_end_date\" timestamptz, \"created_at\" timestamptz default CURRENT_TIMESTAMP, \"updated_at\" timestamptz default CURRENT_TIMESTAMP) - relation \"users\" already exists","name":"error","routine":"heap_create_with_catalog","severity":"ERROR","stack":"error: create table \"users\" (\"id\" serial primary key, \"name\" varchar(255) not null, \"email\" varchar(255) not null, \"password\" varchar(255) not null, \"plan\" text check (\"plan\" in ('free', 'basic', 'premium', 'business')) default 'free', \"trial_end_date\" timestamptz, \"created_at\" timestamptz default CURRENT_TIMESTAMP, \"updated_at\" timestamptz default CURRENT_TIMESTAMP) - relation \"users\" already exists\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:47:10"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist","name":"error","position":"36","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:50:21"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist","name":"error","position":"36","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:50:21"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist","name":"error","position":"36","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:50:21"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist","name":"error","position":"36","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:50:21"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist","name":"error","position":"36","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:50:21"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist","name":"error","position":"36","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - column \"is_draft\" of relation \"flows\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 19:50:21"}
{"code":"42P07","file":"heap.c","length":99,"level":"error","line":"1149","message":"Migration failed: create table \"users\" (\"id\" serial primary key, \"name\" varchar(255) not null, \"email\" varchar(255) not null, \"password\" varchar(255) not null, \"plan\" text check (\"plan\" in ('free', 'basic', 'premium', 'business')) default 'free', \"trial_end_date\" timestamptz, \"created_at\" timestamptz default CURRENT_TIMESTAMP, \"updated_at\" timestamptz default CURRENT_TIMESTAMP) - relation \"users\" already exists","name":"error","routine":"heap_create_with_catalog","severity":"ERROR","stack":"error: create table \"users\" (\"id\" serial primary key, \"name\" varchar(255) not null, \"email\" varchar(255) not null, \"password\" varchar(255) not null, \"plan\" text check (\"plan\" in ('free', 'basic', 'premium', 'business')) default 'free', \"trial_end_date\" timestamptz, \"created_at\" timestamptz default CURRENT_TIMESTAMP, \"updated_at\" timestamptz default CURRENT_TIMESTAMP) - relation \"users\" already exists\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:00:32"}
{"code":"23502","column":"trigger_type","detail":"Failing row contains (1, 1, Fluxo de Teste 1745881365253, null, null, t, 2025-04-28 20:02:45.255-03, 2025-04-28 20:02:45.255-03, t).","file":"execMain.c","length":310,"level":"error","line":"2006","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint","name":"error","routine":"ExecConstraints","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:02:45"}
{"code":"23502","column":"trigger_type","detail":"Failing row contains (2, 1, Test Flow 1745881365255, null, null, t, 2025-04-28 20:02:45.258-03, 2025-04-28 20:02:45.258-03, t).","file":"execMain.c","length":305,"level":"error","line":"2006","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint","name":"error","routine":"ExecConstraints","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:02:45"}
{"code":"23502","column":"trigger_type","detail":"Failing row contains (3, 1, Fluxo de Teste 1745881365304, null, null, t, 2025-04-28 20:02:45.306-03, 2025-04-28 20:02:45.306-03, t).","file":"execMain.c","length":310,"level":"error","line":"2006","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint","name":"error","routine":"ExecConstraints","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:02:45"}
{"code":"23502","column":"trigger_type","detail":"Failing row contains (4, 1, Test Flow 1745881365343, null, null, t, 2025-04-28 20:02:45.344-03, 2025-04-28 20:02:45.344-03, t).","file":"execMain.c","length":305,"level":"error","line":"2006","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint","name":"error","routine":"ExecConstraints","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:02:45"}
{"code":"23502","column":"trigger_type","detail":"Failing row contains (5, 1, Fluxo de Teste 1745881365438, null, null, t, 2025-04-28 20:02:45.439-03, 2025-04-28 20:02:45.439-03, t).","file":"execMain.c","length":310,"level":"error","line":"2006","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint","name":"error","routine":"ExecConstraints","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:02:45"}
{"code":"23502","column":"trigger_type","detail":"Failing row contains (6, 1, Fluxo de Teste 1745881365482, null, null, t, 2025-04-28 20:02:45.483-03, 2025-04-28 20:02:45.483-03, t).","file":"execMain.c","length":310,"level":"error","line":"2006","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint","name":"error","routine":"ExecConstraints","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5) returning * - null value in column \"trigger_type\" of relation \"flows\" violates not-null constraint\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:02:45"}
{"code":"23503","constraint":"flows_user_id_foreign","detail":"Key (user_id)=(1) is not present in table \"users\".","file":"ri_triggers.c","length":248,"level":"error","line":"2608","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"","name":"error","routine":"ri_ReportViolation","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:05:02"}
{"code":"23503","constraint":"flows_user_id_foreign","detail":"Key (user_id)=(1) is not present in table \"users\".","file":"ri_triggers.c","length":248,"level":"error","line":"2608","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"","name":"error","routine":"ri_ReportViolation","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:05:02"}
{"code":"23503","constraint":"flows_user_id_foreign","detail":"Key (user_id)=(1) is not present in table \"users\".","file":"ri_triggers.c","length":248,"level":"error","line":"2608","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"","name":"error","routine":"ri_ReportViolation","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:05:02"}
{"code":"23503","constraint":"flows_user_id_foreign","detail":"Key (user_id)=(1) is not present in table \"users\".","file":"ri_triggers.c","length":248,"level":"error","line":"2608","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"","name":"error","routine":"ri_ReportViolation","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:05:02"}
{"code":"23503","constraint":"flows_user_id_foreign","detail":"Key (user_id)=(1) is not present in table \"users\".","file":"ri_triggers.c","length":248,"level":"error","line":"2608","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"","name":"error","routine":"ri_ReportViolation","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:05:02"}
{"code":"23503","constraint":"flows_user_id_foreign","detail":"Key (user_id)=(1) is not present in table \"users\".","file":"ri_triggers.c","length":248,"level":"error","line":"2608","message":"Erro ao criar fluxo: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"","name":"error","routine":"ri_ReportViolation","schema":"public","severity":"ERROR","stack":"error: insert into \"flows\" (\"created_at\", \"is_draft\", \"name\", \"trigger_type\", \"updated_at\", \"user_id\") values ($1, $2, $3, $4, $5, $6) returning * - insert or update on table \"flows\" violates foreign key constraint \"flows_user_id_foreign\"\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","table":"flows","timestamp":"2025-04-28 20:05:02"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:15:23"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:15:23"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:15:23"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:15:23"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:15:24"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:15:24"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:17:27"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:17:27"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:17:27"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:17:27"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:17:27"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:17:27"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:40:02"}
{"code":"ECONNRESET","errno":-4077,"level":"error","message":"Erro ao listar fluxos: select * from \"flows\" - read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-04-28 20:40:16"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:41:27"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:41:27"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:41:27"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:41:27"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:41:27"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:41:27"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:51:52"}
{"command":{"args":[],"name":"info"},"level":"error","message":"Erro ao verificar status do Redis: NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:179:12)\n    at parseType (C:\\Projetos\\zeplo\\backend\\node_modules\\redis-parser\\lib\\parser.js:302:14)","timestamp":"2025-04-28 20:51:53"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro na query: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:53"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:53"}
{"description":"Instância de teste automatizado","level":"error","message":"Dados da requisição:","name":"test-1745884313229","timestamp":"2025-04-28 20:51:53"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro na query: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:53"}
{"code":"42703","file":"parse_target.c","length":133,"level":"error","line":"1066","message":"Erro ao criar instância: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist","name":"error","position":"40","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"instances\" (\"created_at\", \"description\", \"display_name\", \"evolution_instance_id\", \"name\", \"status\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7) returning * - column \"description\" of relation \"instances\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:53"}
{"description":"Instância de teste automatizado","level":"error","message":"Dados da requisição:","name":"test-1745884313227","timestamp":"2025-04-28 20:51:53"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro na query: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:54"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:54"}
{"email":"test1745884313987@example.com","level":"error","message":"Dados da requisição:","name":"Contato Teste 1745884313987","phone":"55112390828","timestamp":"2025-04-28 20:51:54"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro na query: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:54"}
{"code":"42703","file":"parse_target.c","length":126,"level":"error","line":"1066","message":"Erro ao criar contato: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist","name":"error","position":"39","routine":"checkInsertTargets","severity":"ERROR","stack":"error: insert into \"contacts\" (\"created_at\", \"email\", \"name\", \"notes\", \"phone\", \"updated_at\") values ($1, $2, $3, $4, $5, $6) returning * - column \"email\" of relation \"contacts\" does not exist\n    at Parser.parseErrorMessage (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:187:21)\n    at Parser.parse (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\parser.ts:102:30)\n    at Socket.<anonymous> (C:\\Projetos\\zeplo\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-04-28 20:51:54"}
{"email":"test1745884313989@example.com","level":"error","message":"Dados da requisição:","name":"Contato Teste 1745884313989","phone":"551129097230","timestamp":"2025-04-28 20:51:54"}
{"code":"ECONNRESET","errno":-4077,"level":"error","message":"Redis connection error: read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)","syscall":"read","timestamp":"2025-04-28 22:53:27"}
